- name: Baseligne configuration
  hosts: all
  user: root
  roles:
   - role: base

- name: Install apache2 & dependencies
  hosts: group1
  user: root
  roles:
   - role: apache

- name: postgres install
  hosts: group2
  user: root
  roles:
   - role: postgres

