- name: Baseligne configuration
  hosts: all
  user: root
  roles:
   - role: base

- name: Apache2 install
  hosts: group1
  user: root
  roles:
   - role: apache

- name: postgres install
  hosts: group2
  user: root
  roles:
   - role: postgres
- name: Add a user to a password file and ensure permissions are set
  htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
